/**
 * Populate Supabase ac_inverter_share table
 *
 * Usage:
 *   SUPABASE_SERVICE_KEY=eyJ... node scripts/populate_ac_inverter_share.mjs
 *
 * Prerequisites:
 *   - Table created via: sql/create_ac_inverter_share.sql
 *   - Service role key (anon key is read-only)
 *
 * Data source: AC_SplitInverter_Share.py v2 (99 rows, 51 countries/markets)
 * Scope: SPLIT AC only — window, portable and ducted central AC excluded
 */

const SUPABASE_URL = 'https://hcpmdkkavtadgugrqohl.supabase.co';
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_KEY;

if (!SUPABASE_KEY) {
  console.error('Error: Set SUPABASE_SERVICE_KEY environment variable');
  process.exit(1);
}

// ── helpers ─────────────────────────────────────────────────────────────────

async function insertBatch(table, rows, batchSize = 50) {
  const url = `${SUPABASE_URL}/rest/v1/${table}`;
  let inserted = 0;
  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const res = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        apikey: SUPABASE_KEY,
        Authorization: `Bearer ${SUPABASE_KEY}`,
        Prefer: 'return=minimal',
      },
      body: JSON.stringify(batch),
    });
    if (!res.ok) {
      const err = await res.text();
      throw new Error(`Insert failed (batch ${i / batchSize + 1}): ${res.status} ${err}`);
    }
    inserted += batch.length;
    console.log(`  ${table}: ${inserted}/${rows.length}`);
  }
  return inserted;
}

// ── data ─────────────────────────────────────────────────────────────────────
// Columns: region, country_code, country_name, year_label, year_start, year_end,
//          inverter_pct, inverter_label, non_inverter_pct, non_inverter_label,
//          confidence, is_estimate, scope_notes, source_name, source_url

const ROWS = [

  // ── ASIA – ADVANCED ────────────────────────────────────────────────────────
  {
    region: 'Asia – Advanced', country_code: 'JPN', country_name: 'Japan',
    year_label: '2021', year_start: 2021, year_end: 2021,
    inverter_pct: 100, inverter_label: '~100%',
    non_inverter_pct: 0, non_inverter_label: '~0%',
    confidence: 'High', is_estimate: true,
    scope_notes: 'Split AC essentially 100% inverter for decades. 9.45M RAC units sold (−4.2% YoY). 2.7 units/household. Japan pioneered inverter technology in 1980; near-100% domestic residential by early 2000s. Top Runner Programme.',
    source_name: 'IIF/JARN – Global AC Market (2021)',
    source_url: 'https://iifiir.org/en/news/the-global-air-conditioning-market-in-2021-focus-on-africa',
  },
  {
    region: 'Asia – Advanced', country_code: 'JPN', country_name: 'Japan',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 100, inverter_label: '~100%',
    non_inverter_pct: 0, non_inverter_label: '~0%',
    confidence: 'High', is_estimate: true,
    scope_notes: '9.3M RAC units (+6.2% YoY). "In the Japanese residential market, inverter ACs account for almost 100% of the market." (HPT Mag, 2024)',
    source_name: 'IIF/JARN – Global AC Market 2024 (Jan 2025)',
    source_url: 'https://iifiir.org/en/news/global-air-conditioner-market-2024-performance',
  },
  {
    region: 'Asia – Advanced', country_code: 'KOR', country_name: 'South Korea',
    year_label: '2022', year_start: 2022, year_end: 2022,
    inverter_pct: 98, inverter_label: '~98% (est.)',
    non_inverter_pct: 2, non_inverter_label: '~2% (est.)',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'Near-100% inverter penetration for residential split AC. Samsung and LG dominate with exclusively inverter product lines. Korea Top Runner MEPS. No official government % found; estimate from market structure evidence.',
    source_name: 'Expert Market Research / Bonafide Research (South Korea AC Market)',
    source_url: 'https://www.expertmarketresearch.com/reports/south-korea-air-conditioner-market',
  },
  {
    region: 'Asia – Advanced', country_code: 'SGP', country_name: 'Singapore',
    year_label: '2021', year_start: 2021, year_end: 2021,
    inverter_pct: 90, inverter_label: '~90% (est.)',
    non_inverter_pct: 10, non_inverter_label: '~10% (est.)',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'AC ownership >80% of households. Only 21% "low-efficiency" units vs 74% SE Asia average — highest efficiency in SE Asia. BCA Green Mark scheme drives inverter adoption. 90% of units used R-410A.',
    source_name: 'CLASP – Pathways to Prevent Dumping: SE Asia (2021)',
    source_url: 'https://www.clasp.ngo/research/all/pathways-to-prevent-dumping-of-climate-harming-room-air-conditioners-in-southeast-asia/',
  },

  // ── OCEANIA ────────────────────────────────────────────────────────────────
  {
    region: 'Oceania', country_code: 'AUS', country_name: 'Australia',
    year_label: '2009–12', year_start: 2009, year_end: 2012,
    inverter_pct: 60, inverter_label: '~60% (est.)',
    non_inverter_pct: 40, non_inverter_label: '~40% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '2009 GEMS Decision RIS introduced variable-speed compliance pathway. Inverter models growing rapidly post-2009 MEPS. Daikin, Mitsubishi, Fujitsu, Panasonic all shifted to inverter-only by ~2013–2015.',
    source_name: 'DCCEEW / Energy Rating Decision RIS 2009',
    source_url: 'https://www.energyrating.gov.au/sites/default/files/2022-12/Decision_RIS_-_Air_Conditioner_MEPS_and_Energy_Labelling_April_2009.pdf',
  },
  {
    region: 'Oceania', country_code: 'AUS', country_name: 'Australia',
    year_label: '2016–18', year_start: 2016, year_end: 2018,
    inverter_pct: 88, inverter_label: '~88% (est.)',
    non_inverter_pct: 12, non_inverter_label: '~12% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: 'All major brands (Daikin, Mitsubishi, Fujitsu, Panasonic, Samsung, LG) already inverter-only by ~2015. Remaining non-inverter: budget portable/window and ActronAir (last major holdout in split). Cold Hard Facts 3 (2018) confirms inverter domination.',
    source_name: 'DCCEEW Cold Hard Facts 3 (2018) + E3 Programme trend data',
    source_url: 'https://www.dcceew.gov.au/sites/default/files/documents/cold-hard-facts3.pdf',
  },
  {
    region: 'Oceania', country_code: 'AUS', country_name: 'Australia',
    year_label: '2020–21', year_start: 2020, year_end: 2021,
    inverter_pct: 95, inverter_label: '~95% (est.)',
    non_inverter_pct: 5, non_inverter_label: '~5% (est.)',
    confidence: 'Medium', is_estimate: true,
    scope_notes: '1.09M non-ducted split systems sold. HFC-32 refrigerant (exclusively in inverter split ACs) = 38%+ of installed stock and 60%+ of new split imports by 2021. Energy Rating website: "Variable speed ACs (inverters) now dominate the market."',
    source_name: 'DCCEEW Cold Hard Facts 2022 + Energy Rating AU',
    source_url: 'https://www.dcceew.gov.au/sites/default/files/documents/cold-hard-facts-2022.pdf',
  },
  {
    region: 'Oceania', country_code: 'AUS', country_name: 'Australia',
    year_label: '2022–24', year_start: 2022, year_end: 2024,
    inverter_pct: 98, inverter_label: '~98% (est.)',
    non_inverter_pct: 2, non_inverter_label: '~2% (est.)',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'HFC-32 = 94–96% of all new non-ducted split system imports by 2022 — HFC-32 used exclusively in inverter-type split systems. ActronAir completed inverter-only transition in 2022. GEMS Determination 2019 + Zoned Energy Rating Label (from Apr 2020) effectively mandate inverter for all new residential split sales.',
    source_name: 'DCCEEW Cold Hard Facts 2022 + ActronAir statement (March 2022)',
    source_url: 'https://actronair.com.au/2022/03/17/what-is-inverter-air-conditioning/',
  },
  {
    region: 'Oceania', country_code: 'NZL', country_name: 'New Zealand',
    year_label: '2015–19', year_start: 2015, year_end: 2019,
    inverter_pct: 90, inverter_label: '~90% (est.)',
    non_inverter_pct: 10, non_inverter_label: '~10% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: 'EECA (NZ) confirms "variable speed ACs (inverters) now dominate the market." NZ follows same AS/NZS 3823.2 MEPS as Australia via shared E3 Programme. 25%+ of NZ homes have heat pumps (= split reverse-cycle) — virtually all inverter post-2010.',
    source_name: 'EECA NZ – E3 Programme Sales and Efficiency Data',
    source_url: 'https://www.eeca.govt.nz/insights/eeca-insights/e3-programme-sales-and-efficiency-data/',
  },
  {
    region: 'Oceania', country_code: 'NZL', country_name: 'New Zealand',
    year_label: '2020–24', year_start: 2020, year_end: 2024,
    inverter_pct: 97, inverter_label: '~97% (est.)',
    non_inverter_pct: 3, non_inverter_label: '~3% (est.)',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'Same brand landscape and E3 MEPS standards as Australia. EECA: "Variable speed ACs now dominate the market." NZ Energy Efficiency Amendment Regulations 2020 (in force 1 Jul 2021) tightened MEPS. All major retailers sell exclusively inverter split systems.',
    source_name: 'EECA NZ / E3 Programme + 2020 Regulations',
    source_url: 'https://www.eeca.govt.nz/regulations/equipment-energy-efficiency/about-the-e3-programme/products-under-e3/air-conditioners-65-kw-and-under/',
  },

  // ── ASIA – EMERGING (China) ────────────────────────────────────────────────
  {
    region: 'Asia – Emerging', country_code: 'CHN', country_name: 'China',
    year_label: '2017', year_start: 2017, year_end: 2017,
    inverter_pct: 53, inverter_label: '53%',
    non_inverter_pct: 47, non_inverter_label: '47%',
    confidence: 'High', is_estimate: false,
    scope_notes: 'Split AC domestic sales. Baseline before GB 21455-2019 MEPS. IIR/CLASP: share rose from 53% (2017) to 95% (2021) driven by MEPS. China produces ~80% of global RACs.',
    source_name: 'IIR – Positive Impact of MEPS on China AC Market',
    source_url: 'https://iifiir.org/en/news/positive-impact-of-recent-meps-on-the-air-conditioner-market-in-china',
  },
  {
    region: 'Asia – Emerging', country_code: 'CHN', country_name: 'China',
    year_label: '2018', year_start: 2018, year_end: 2018,
    inverter_pct: 70, inverter_label: '70%',
    non_inverter_pct: 30, non_inverter_label: '30%',
    confidence: 'High', is_estimate: false,
    scope_notes: 'Retail split RAC. Grade-1 EE ACs = 44% of market; EE growth +14% YoY. Total RAC: 59.5M units (−2.3%). China produces ~70% of global RACs.',
    source_name: 'IIF/JARN – World AC Market Trends (Jan 2019)',
    source_url: 'https://iifiir.org/en/news/world-air-conditioning-market-figures-and-technical-trends',
  },
  {
    region: 'Asia – Emerging', country_code: 'CHN', country_name: 'China',
    year_label: '2019 (pre-MEPS)', year_start: 2019, year_end: 2019,
    inverter_pct: 60, inverter_label: '~60%',
    non_inverter_pct: 40, non_inverter_label: '~40%',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'Pre-MEPS baseline before GB 21455-2019 enforcement (effective Jul 2020). CLASP: share cited as ~60% at time MEPS took effect; rose to ~98% within 2 years.',
    source_name: 'CLASP – China MEPS Market Transformation',
    source_url: 'https://www.clasp.ngo/research/all/chinas-meps-lead-to-major-ac-market-transformation/',
  },
  {
    region: 'Asia – Emerging', country_code: 'CHN', country_name: 'China',
    year_label: '2021 (all-RAC annual avg)', year_start: 2021, year_end: 2021,
    inverter_pct: 73.5, inverter_label: '73.5%',
    non_inverter_pct: 26.5, non_inverter_label: '26.5%',
    confidence: 'High', is_estimate: false,
    scope_notes: 'All RAC annual average (IIF/JARN). Market +2.6% vs 2020. AC penetration 117.7 per 100 households. NOTE: CLASP cites 95% for split AC new sales by end-2021 (after Jul 2020 MEPS enforcement); 73.5% is annual average incl. first half when non-compliant stock still sold.',
    source_name: 'ZERO US Partners (JARN 2021 data)',
    source_url: 'https://zeroac.us/world-air-conditioner-market/',
  },
  {
    region: 'Asia – Emerging', country_code: 'CHN', country_name: 'China',
    year_label: '2021 (new split sales)', year_start: 2021, year_end: 2021,
    inverter_pct: 95, inverter_label: '95%',
    non_inverter_pct: 5, non_inverter_label: '5%',
    confidence: 'High', is_estimate: false,
    scope_notes: 'Split RAC new sales share by end-2021 after GB 21455-2019 enforcement (Jul 2020). "Share of inverter ACs soared from 53% in 2017 to 95% in 2021." Grade-1 share: 19%→56%. CO2 prevented 2020–2030: min. 470 Mt.',
    source_name: 'IIR – Positive Impact of MEPS on China AC Market (2023)',
    source_url: 'https://iifiir.org/en/news/positive-impact-of-recent-meps-on-the-air-conditioner-market-in-china',
  },
  {
    region: 'Asia – Emerging', country_code: 'CHN', country_name: 'China',
    year_label: '2022', year_start: 2022, year_end: 2022,
    inverter_pct: 98, inverter_label: '~98%',
    non_inverter_pct: 2, non_inverter_label: '~2%',
    confidence: 'High', is_estimate: true,
    scope_notes: 'Post GB 21455-2019 full enforcement. Variable-speed "quickly rising from 60% to 98% since implementation of new MEPS." Fixed-speed effectively eliminated from new residential split sales.',
    source_name: 'CLASP – China MEPS Market Transformation',
    source_url: 'https://www.clasp.ngo/research/all/chinas-meps-lead-to-major-ac-market-transformation/',
  },

  // ── ASIA – EMERGING (India) ────────────────────────────────────────────────
  {
    region: 'Asia – Emerging', country_code: 'IND', country_name: 'India',
    year_label: '2015–16', year_start: 2015, year_end: 2016,
    inverter_pct: 0.5, inverter_label: '<1%',
    non_inverter_pct: 99, non_inverter_label: '>99%',
    confidence: 'High', is_estimate: false,
    scope_notes: 'Split RAC. BEE official data. Total RAC market 4.7M units. BEE introduced voluntary ISEER labelling for inverter RACs in June 2015.',
    source_name: 'India PIB / BEE (official govt data)',
    source_url: 'https://www.pib.gov.in/PressReleaseIframePage.aspx?PRID=1923031',
  },
  {
    region: 'Asia – Emerging', country_code: 'IND', country_name: 'India',
    year_label: '2017', year_start: 2017, year_end: 2017,
    inverter_pct: 15, inverter_label: '~15%',
    non_inverter_pct: 85, non_inverter_label: '~85%',
    confidence: 'High', is_estimate: true,
    scope_notes: 'Split RAC. Inverter still nascent; 20–25% price premium barrier. ISEER mandatory labelling from Jan 2018. LG was first to shift full lineup to inverter in 2017, driving rapid market change.',
    source_name: 'IIF/JARN – World AC Market Trends (Jan 2019)',
    source_url: 'https://iifiir.org/en/news/world-air-conditioning-market-figures-and-technical-trends',
  },
  {
    region: 'Asia – Emerging', country_code: 'IND', country_name: 'India',
    year_label: '2018', year_start: 2018, year_end: 2018,
    inverter_pct: 35, inverter_label: '35%',
    non_inverter_pct: 65, non_inverter_label: '65%',
    confidence: 'High', is_estimate: false,
    scope_notes: 'Split RAC. JARN: 35% for 2018. BEE/CLASP separately cite 54% for same year — discrepancy due to timing within year of ISEER mandatory rollout (Jan 2018). Inverter share more than doubled YoY.',
    source_name: 'IIF/JARN – World AC Market Trends (Jan 2019)',
    source_url: 'https://iifiir.org/en/news/world-air-conditioning-market-figures-and-technical-trends',
  },
  {
    region: 'Asia – Emerging', country_code: 'IND', country_name: 'India',
    year_label: '~2019', year_start: 2019, year_end: 2019,
    inverter_pct: 60, inverter_label: '~60%',
    non_inverter_pct: 40, non_inverter_label: '~40%',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'Split RAC. CLASP: "BEE policies increased inverter share from 1% in 2015 to close to 60% in 2019." Corroborated by SOIC analysis.',
    source_name: 'CLASP – Increasing Access to ACs in a Heating India',
    source_url: 'https://www.clasp.ngo/updates/increasing-access-to-air-conditioners-in-a-heating-india/',
  },
  {
    region: 'Asia – Emerging', country_code: 'IND', country_name: 'India',
    year_label: '2021', year_start: 2021, year_end: 2021,
    inverter_pct: 45, inverter_label: '~45%',
    non_inverter_pct: 55, non_inverter_label: '~55%',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'All RAC (incl. window). Total RAC market 6.6M units (+23% YoY). IIF/JARN note: inverter "above 60% in all major Asian markets except India (45%)".',
    source_name: 'IIF/JARN – Global AC Market (2021)',
    source_url: 'https://iifiir.org/en/news/the-global-air-conditioning-market-in-2021-focus-on-africa',
  },
  {
    region: 'Asia – Emerging', country_code: 'IND', country_name: 'India',
    year_label: '2022–23', year_start: 2022, year_end: 2023,
    inverter_pct: 77, inverter_label: '77%',
    non_inverter_pct: 23, non_inverter_label: '23%',
    confidence: 'High', is_estimate: false,
    scope_notes: 'Split RAC (BEE official data). India Ministry of Power: "During eight years from 2015–16 to 2022–23, inverter RAC share increased from 1% to 77%, fixed-speed reduced from 99% to 23%."',
    source_name: 'India PIB / BEE (official govt data, May 2023)',
    source_url: 'https://www.pib.gov.in/PressReleaseIframePage.aspx?PRID=1923031',
  },
  {
    region: 'Asia – Emerging', country_code: 'IND', country_name: 'India',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 85, inverter_label: '~85% (est.)',
    non_inverter_pct: 15, non_inverter_label: '~15% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: '[EST] Extrapolated from FY23 BEE figure of 77% + accelerating trend. BEE 2024 revised standards mandate inverter for higher star ratings. Inverter premium over fixed-speed fell below 8%. Total RAC market 12.5M units (+35% overall).',
    source_name: 'IIF/JARN – Global AC Market 2024 + BEE trend',
    source_url: 'https://iifiir.org/en/news/global-air-conditioner-market-2024-performance',
  },

  // ── ASIA – EMERGING (SE Asia) ──────────────────────────────────────────────
  {
    region: 'Asia – Emerging', country_code: 'THA', country_name: 'Thailand',
    year_label: '2013', year_start: 2013, year_end: 2013,
    inverter_pct: 16, inverter_label: '16%',
    non_inverter_pct: 84, non_inverter_label: '84%',
    confidence: 'Medium', is_estimate: false,
    scope_notes: 'Split RAC. CLASP Thailand Market Assessment 2019: share of available inverter models on market in 2013. Baseline before TISI energy label expansion. Note: model-availability share; sales volume share for small units was higher.',
    source_name: 'CLASP – Thailand RAC Market Assessment 2019',
    source_url: 'https://www.clasp.ngo/research/all/thailand-rac-market-assessment-and-policy-options-analysis-2019/',
  },
  {
    region: 'Asia – Emerging', country_code: 'THA', country_name: 'Thailand',
    year_label: '2016', year_start: 2016, year_end: 2016,
    inverter_pct: 30, inverter_label: '~30%',
    non_inverter_pct: 70, non_inverter_label: '~70%',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'Split RAC. JARN baseline cited as "two years prior to 2018". TISI energy label driving adoption. AC ownership 55% of households (2021).',
    source_name: 'IIF/JARN – World AC Market Trends (Jan 2019)',
    source_url: 'https://iifiir.org/en/news/world-air-conditioning-market-figures-and-technical-trends',
  },
  {
    region: 'Asia – Emerging', country_code: 'THA', country_name: 'Thailand',
    year_label: '2018', year_start: 2018, year_end: 2018,
    inverter_pct: 50, inverter_label: '50%',
    non_inverter_pct: 50, non_inverter_label: '50%',
    confidence: 'High', is_estimate: false,
    scope_notes: 'Split RAC. Inverter share doubled from ~30% in ~2 years, driven by TISI energy label and consumer awareness of running-cost savings.',
    source_name: 'IIF/JARN – World AC Market Trends (Jan 2019)',
    source_url: 'https://iifiir.org/en/news/world-air-conditioning-market-figures-and-technical-trends',
  },
  {
    region: 'Asia – Emerging', country_code: 'THA', country_name: 'Thailand',
    year_label: '2019 (model share)', year_start: 2019, year_end: 2019,
    inverter_pct: 32, inverter_label: '32% (models)',
    non_inverter_pct: 68, non_inverter_label: '68%',
    confidence: 'Medium', is_estimate: false,
    scope_notes: 'Model-availability share per CLASP 2019 retail survey (sub-60K BTU). "Market share of inverter units doubled since 2013, from 16% to 32%." Note: model-count share; sales volume share was higher for small units.',
    source_name: 'CLASP – Thailand RAC Market Assessment 2019',
    source_url: 'https://www.clasp.ngo/research/all/thailand-rac-market-assessment-and-policy-options-analysis-2019/',
  },
  {
    region: 'Asia – Emerging', country_code: 'THA', country_name: 'Thailand',
    year_label: '2023–24', year_start: 2023, year_end: 2024,
    inverter_pct: 72, inverter_label: '~72% (new launches)',
    non_inverter_pct: 28, non_inverter_label: '~28%',
    confidence: 'Medium', is_estimate: true,
    scope_notes: '"72% of newly launched units feature inverter compressors." (Astute Analytica). 56% of customers cite lower electricity bills as key purchase driver. 2022 revised MEPS effectively phased out non-inverter models below 24,000 BTU.',
    source_name: 'Astute Analytica / GlobeNewsWire – Thailand AC Market 2033 Outlook',
    source_url: 'https://www.globenewswire.com/news-release/2025/01/01/3003242/0/en/Thailand-Air-Conditioner-Market-to-Worth-Over-US-2-937-83-Million-By-2033-Market-Share-Innovation-and-Consumer-Demand-Analysis.html',
  },
  {
    region: 'Asia – Emerging', country_code: 'VNM', country_name: 'Vietnam',
    year_label: '2013', year_start: 2013, year_end: 2013,
    inverter_pct: 34, inverter_label: '~34%',
    non_inverter_pct: 66, non_inverter_label: '~66%',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'Split RAC. CLASP SEA data baseline. Vietnam had "largest inverter AC penetration" in SE Asia at time of assessment. Market largely imports-based.',
    source_name: 'CLASP – Vietnam RAC Market Assessment 2019',
    source_url: 'https://www.clasp.ngo/research/all/vietnam-rac-market-assessment-and-policy-options-analysis-2019/',
  },
  {
    region: 'Asia – Emerging', country_code: 'VNM', country_name: 'Vietnam',
    year_label: '2019', year_start: 2019, year_end: 2019,
    inverter_pct: 65, inverter_label: '65%',
    non_inverter_pct: 35, non_inverter_label: '35%',
    confidence: 'Medium', is_estimate: false,
    scope_notes: 'Split RAC. CLASP: inverter share grew from 34% (2013) to 65% (2019) over 6 years. Growth driven by CSPF seasonal metric introduced 2015. Vietnam was most inverter-advanced SEA market at this date.',
    source_name: 'CLASP – Vietnam RAC Market Assessment 2019',
    source_url: 'https://www.clasp.ngo/research/all/vietnam-rac-market-assessment-and-policy-options-analysis-2019/',
  },
  {
    region: 'Asia – Emerging', country_code: 'PHL', country_name: 'Philippines',
    year_label: '2019', year_start: 2019, year_end: 2019,
    inverter_pct: 38, inverter_label: '~38% (split share of all RAC)',
    non_inverter_pct: 62, non_inverter_label: '~62% (window-type dominates)',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'CLASP Philippines Market Assessment 2019. Unique market: Philippines is the ONLY SEA country dominated by fixed-speed window-type ACs (62% of total RAC market). Among split-type only, inverter share was growing. "Local producers hold over 50% of AC market share." 38% = split-type inverter as fraction of ALL room ACs.',
    source_name: 'CLASP – Philippines RAC Market Assessment 2019',
    source_url: 'https://www.clasp.ngo/research/all/philippines-rac-market-assessment-and-policy-options-analysis-2019/',
  },
  {
    region: 'Asia – Emerging', country_code: 'IDN', country_name: 'Indonesia',
    year_label: '2019', year_start: 2019, year_end: 2019,
    inverter_pct: 8, inverter_label: '8%',
    non_inverter_pct: 92, non_inverter_label: '92%',
    confidence: 'High', is_estimate: false,
    scope_notes: 'All RAC (split dominant). LBNL: "Only 8% inverter penetration vs 40% SE Asia avg and 65% China avg." 97% of Indonesia\'s AC stock classified as "low efficiency" in 2021 (highest of all SEA countries per CLASP). Urban AC ownership rose 15%→29% (2015–2023).',
    source_name: 'LBNL – Baseline Evaluation Indonesia ACs',
    source_url: 'https://eta-publications.lbl.gov/sites/default/files/eedal_conference_paper_baseline_evaluation_and_policy_implications_for_air_conditioners_in_indonesia_final.pdf',
  },
  {
    region: 'Asia – Emerging', country_code: 'MYS', country_name: 'Malaysia',
    year_label: '2021', year_start: 2021, year_end: 2021,
    inverter_pct: 61.5, inverter_label: '~58–65%',
    non_inverter_pct: 38.5, non_inverter_label: '~35–42%',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'U4E/UNEP Market Assessment 2024: "58% of certified models registered in 2021 were inverter type; retail shelf survey showed 65% of available models were inverter type." Annual sales ~790,000 units. AC ownership >80% of households (highest in SE Asia). SIRIM EE label scheme.',
    source_name: 'U4E / UNEP – Market Assessment High-Efficient Climate-Friendly ACs (2024)',
    source_url: 'https://united4efficiency.org/wp-content/uploads/2024/03/AC-Market-Assessment-Report_Final_240518.pdf',
  },
  {
    region: 'Asia – Emerging', country_code: 'PAK', country_name: 'Pakistan',
    year_label: '2022–23', year_start: 2022, year_end: 2023,
    inverter_pct: 80, inverter_label: '~80% (est.)',
    non_inverter_pct: 20, non_inverter_label: '~20% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] All major brands (Haier, Gree, Dawlance, PEL, Kenwood, Orient) market DC inverter models near-exclusively. Pakistan\'s chronic electricity load-shedding crisis makes inverter ACs effectively essential. Market USD 500M+. No official government % found; estimate from market structure and brand product range analysis.',
    source_name: '6W Research – Pakistan AC Market 2017–2023',
    source_url: 'https://www.6wresearch.com/industry-report/pakistan-air-conditioner-market-2017-2023-forecast-by-type-applications-regions-competitive-landscape',
  },

  // ── ASIA – EMERGING (regional aggregates) ─────────────────────────────────
  {
    region: 'Asia – Emerging', country_code: null, country_name: 'SE Asia (overall)',
    year_label: '2021', year_start: 2021, year_end: 2021,
    inverter_pct: 55, inverter_label: '~55% (est.)',
    non_inverter_pct: 45, non_inverter_label: '~45% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: '[EST] Weighted avg of country shares by market size (8.3M total units): Thailand ~2.7M×65%, Indonesia ~2M×15%, Vietnam ~1.5M×65%, Philippines ~1M×38%, Malaysia ~0.8M×62%, Singapore ~0.3M×90%. 74% of ACs region-wide classified "low-efficiency" incl. old stock.',
    source_name: 'IIF/JARN (2021) + CLASP/BSRIA country-level data weighted',
    source_url: 'https://iifiir.org/en/news/the-global-air-conditioning-market-in-2021-focus-on-africa',
  },
  {
    region: 'Asia – Emerging', country_code: null, country_name: 'Asia-Pacific (17 markets)',
    year_label: '~2019', year_start: 2019, year_end: 2019,
    inverter_pct: 60, inverter_label: '60%',
    non_inverter_pct: 40, non_inverter_label: '40%',
    confidence: 'High', is_estimate: false,
    scope_notes: 'BSRIA expanded Asia-Pacific AC market study covering 17 countries: Australia, Bangladesh, Cambodia, China, Hong Kong, India, Indonesia, Japan, Malaysia, New Zealand, Pakistan, Philippines, Singapore, South Korea, Taiwan, Thailand, Vietnam. Baseline inverter penetration rate in split AC.',
    source_name: 'BSRIA – Expanded Asia Pacific AC Market Study',
    source_url: 'https://refindustry.com/news/market-research/bsria-s-expanded-asia-pacific-air-conditioning-market-coverage-shows-increasing-influence-of-energy-/',
  },
  {
    region: 'Asia – Emerging', country_code: null, country_name: 'Asia-Pacific (17 markets)',
    year_label: '~2021–22', year_start: 2021, year_end: 2022,
    inverter_pct: 76, inverter_label: '76%',
    non_inverter_pct: 24, non_inverter_label: '24%',
    confidence: 'High', is_estimate: false,
    scope_notes: 'BSRIA 17-country Asia-Pacific study update. "Average penetration rate of inverters in splits has now reached 76% compared to just 60% in 2019." Chillers also rose from 12% to 24% inverter. Driven by China MEPS (Jul 2020) and India BEE programme.',
    source_name: 'BSRIA – Expanded Asia Pacific AC Market Study',
    source_url: 'https://refindustry.com/news/market-research/bsria-s-expanded-asia-pacific-air-conditioning-market-coverage-shows-increasing-influence-of-energy-/',
  },

  // ── LATIN AMERICA ──────────────────────────────────────────────────────────
  {
    region: 'Latin America', country_code: 'BRA', country_name: 'Brazil',
    year_label: 'pre-2022 (old label)', year_start: null, year_end: 2022,
    inverter_pct: 20, inverter_label: '~20% (model portfolio)',
    non_inverter_pct: 80, non_inverter_label: '~80%',
    confidence: 'Medium', is_estimate: false,
    scope_notes: 'Under old INMETRO ENCE label system (pre-Jan 2023 MEPS): only ~20% of INMETRO-certified AC model portfolio was inverter; 80% on/off. This is registered model portfolio share, not necessarily sales volume. New MEPS (Apr 2022) took effect Jan 2023, banning non-compliant manufacture.',
    source_name: 'INMETRO / CLASP – Brazil AC Policy Analysis',
    source_url: 'https://www.clasp.ngo/updates/brazils-latest-ac-policy-to-dramatically-cut-costs-and-emissions/',
  },
  {
    region: 'Latin America', country_code: 'BRA', country_name: 'Brazil',
    year_label: '2018', year_start: 2018, year_end: 2018,
    inverter_pct: 50, inverter_label: '~50%',
    non_inverter_pct: 50, non_inverter_label: '~50%',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'Residential split AC. Eletrobras 2021 data cited by CLASP: "Inverter = 50% of residential AC sales" by 2018. Brazil/Mexico/Argentina = 77% of Latin America total sales. PROCEL energy label introduced in 2020.',
    source_name: 'CLASP – Brazil AC Policy Analysis',
    source_url: 'https://www.clasp.ngo/updates/brazils-latest-ac-policy-to-dramatically-cut-costs-and-emissions/',
  },
  {
    region: 'Latin America', country_code: 'BRA', country_name: 'Brazil',
    year_label: 'Jan 2023 (new MEPS)', year_start: 2023, year_end: 2023,
    inverter_pct: 91, inverter_label: '91% (of models)',
    non_inverter_pct: 9, non_inverter_label: '9%',
    confidence: 'High', is_estimate: false,
    scope_notes: 'INMETRO data (Jan 2023): 218 of 239 available AC models (up to 36,000 BTU/h) are inverter = 91%. New MEPS took effect Jan 2023 banning manufacture/import of non-compliant (mostly fixed-speed) units. New ENCE label: only inverter units can achieve "A" class under CSPF/ICSF.',
    source_name: 'INMETRO / ASMETRO-SI (Brazil new efficiency label, Jan 2023)',
    source_url: 'https://asmetro.org.br/portalsn/2023/01/28/aparelhos-de-ar-condicionado-com-a-nova-classificacao-de-eficiencia-energetica-estabelecida-pelo-inmetro/',
  },
  {
    region: 'Latin America', country_code: 'BRA', country_name: 'Brazil',
    year_label: '2023–24', year_start: 2023, year_end: 2024,
    inverter_pct: 89, inverter_label: '~89%',
    non_inverter_pct: 11, non_inverter_label: '~11%',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'Residential split AC. PROCEL-certified inverter ACs dominate 89% of new installations. Manufacturing/import ban on non-compliant ACs: Jan 2023. Marketing ban (all retailers): Jan 2025. Split AC production +71.3% H1 2024.',
    source_name: 'CLASP – Brazil AC Policy Analysis',
    source_url: 'https://www.clasp.ngo/updates/brazils-latest-ac-policy-to-dramatically-cut-costs-and-emissions/',
  },
  {
    region: 'Latin America', country_code: 'BRA', country_name: 'Brazil',
    year_label: '2024+', year_start: 2024, year_end: null,
    inverter_pct: 95, inverter_label: '~95%+ (est.)',
    non_inverter_pct: 5, non_inverter_label: '~5% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Jan 2025 marketing ban on non-compliant fixed-speed units took full effect; market now effectively 95%+ inverter for new split AC sales. No post-ban published figure available. Estimate based on regulatory timeline extrapolation.',
    source_name: 'CLASP – Brazil AC Policy / MEPS timeline',
    source_url: 'https://www.clasp.ngo/updates/brazils-latest-ac-policy-to-dramatically-cut-costs-and-emissions/',
  },
  {
    region: 'Latin America', country_code: 'MEX', country_name: 'Mexico',
    year_label: '2020', year_start: 2020, year_end: 2020,
    inverter_pct: 52, inverter_label: '>50%',
    non_inverter_pct: 48, non_inverter_label: '<50%',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'ANFAD (Mexico AC Manufacturers Association): ">50% of domestic AC equipment sold were inverter mini-splits from 2020 onward." Mini-split is the dominant product in Mexico. NOM-023-ENER-2018 MEPS in force.',
    source_name: 'ANFAD via Mundo HVAC&R – La era inverter ya está en casa (2020)',
    source_url: 'https://www.mundohvacr.com/2020/01/la-era-inverter-ya-esta-en-casa-confort-y-eficiencia-energetica-para-el-mercado-mexicano/',
  },
  {
    region: 'Latin America', country_code: 'MEX', country_name: 'Mexico',
    year_label: '~2022–23', year_start: 2022, year_end: 2023,
    inverter_pct: 65, inverter_label: '~65% (est.)',
    non_inverter_pct: 35, non_inverter_label: '~35% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: '[EST] ANFAD projected inverter to exceed 70% by 2023. BSRIA characterised Mexico\'s inverter conversion as "still slow" vs broader LAC — suggesting actual may be lower (55–70% range). R32 refrigerant at 38% of single split segment (BSRIA) is proxy for inverter. Midpoint 65% used.',
    source_name: 'ANFAD / Mundo HVAC&R (2023); BSRIA World AC Market Insights 2023',
    source_url: 'https://www.mundohvacr.com/2023/01/estimaciones-de-crecimiento-para-el-mercado-hvac-en-el-2023/',
  },
  {
    region: 'Latin America', country_code: 'ARG', country_name: 'Argentina',
    year_label: '2022', year_start: 2022, year_end: 2022,
    inverter_pct: 26, inverter_label: '26%',
    non_inverter_pct: 74, non_inverter_label: '74%',
    confidence: 'High', is_estimate: false,
    scope_notes: 'PRIMARY SOURCE: Afarte (Argentine AC Manufacturers Association) stated inverter = 26% of split AC sales in 2022. Splits = 80% of total AC market. Price barrier cited as key reason for low inverter share vs Brazil. Total: ~1.3M units manufactured.',
    source_name: 'Afarte via Revista Integración Empresaria (Argentina)',
    source_url: 'https://integracionempresaria.com.ar/acondicionadores-de-aire-buenas-expectativas-en-todo-el-mercado/',
  },
  {
    region: 'Latin America', country_code: 'ARG', country_name: 'Argentina',
    year_label: '2023', year_start: 2023, year_end: 2023,
    inverter_pct: 30, inverter_label: '~30% (est.)',
    non_inverter_pct: 70, non_inverter_label: '~70% (est.)',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'Manufacturers stated inverter had "already climbed to 30%" by 2023. [EST] Consistent with 2022 Afarte figure of 26% + upward trend. Market ~1.3–1.4M total units. La Nación (April 2023) reported inverter growth. No MEPS mandate for inverter; adoption demand-driven.',
    source_name: 'Manufacturers via La Nación (Argentina) April 2023',
    source_url: 'https://www.lanacion.com.ar/economia/negocios/aire-acondicionado-los-grandes-ganadores-de-la-ola-de-calor-nid01042023/',
  },
  {
    region: 'Latin America', country_code: null, country_name: 'Latin America (overall)',
    year_label: '2021', year_start: 2021, year_end: 2021,
    inverter_pct: 40, inverter_label: '~40% (est.)',
    non_inverter_pct: 60, non_inverter_label: '~60% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Weighted estimate: Brazil (~50% in 2018, rising), Mexico (~50%+), Argentina (~25%), rest of region (<35%). Brazil/Mexico/Argentina = 77% of 9.37M total units.',
    source_name: 'ZERO US Partners (JARN 2021) + country-level estimates',
    source_url: 'https://zeroac.us/world-air-conditioner-market/',
  },
  {
    region: 'Latin America', country_code: null, country_name: 'Latin America (overall)',
    year_label: '2023', year_start: 2023, year_end: 2023,
    inverter_pct: 48, inverter_label: '~48% (est.)',
    non_inverter_pct: 52, non_inverter_label: '~52% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: '[EST] BSRIA 2023: "the ratio of split inverter has now passed the 40% threshold in ALL countries in the region" — documented floor, not avg. Brazil (~89%), Mexico (~65%), Argentina (~30%) weighted with rest-of-region at >40% gives regional avg ~48%.',
    source_name: 'BSRIA via Designing Buildings / RefinIndustry (Latin America AC 2023)',
    source_url: 'https://www.designingbuildings.co.uk/wiki/Good_Potential_for_AC_Growth_in_Latin_America_despite_challenges_ahead',
  },

  // ── AFRICA ─────────────────────────────────────────────────────────────────
  {
    region: 'Africa', country_code: null, country_name: 'Africa (overall)',
    year_label: '2021', year_start: 2021, year_end: 2021,
    inverter_pct: 18, inverter_label: '~18% (est.)',
    non_inverter_pct: 82, non_inverter_label: '~82% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: '[EST] Source states "<20%"; midpoint 18% used. 3.44M units, +3.1%. ~35% of African RACs have EER <3.0 W/W. Import taxes >40% make inverter premium unaffordable for most buyers.',
    source_name: 'IIF/JARN – Africa Focus (2021) via iClimaAir',
    source_url: 'https://iifiir.org/en/news/the-global-air-conditioning-market-in-2021-focus-on-africa',
  },
  {
    region: 'Africa', country_code: null, country_name: 'Africa (overall)',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 41.8, inverter_label: '41.8%',
    non_inverter_pct: 58.2, non_inverter_label: '58.2%',
    confidence: 'Medium', is_estimate: false,
    scope_notes: 'All Africa AC market. SOURCED: "Non-inverter segment was prevailing technology in Africa at 58.2% of total unit sales in 2024." Egypt largest market (~960K units), followed by Nigeria (~840K), Algeria (600K+), South Africa (~400K).',
    source_name: 'MarketDataForecast – Africa Air Conditioner Market 2024',
    source_url: 'https://www.marketdataforecast.com/market-reports/africa-air-conditioner-market',
  },
  {
    region: 'Africa', country_code: 'ZAF', country_name: 'South Africa',
    year_label: '~2022', year_start: 2022, year_end: 2022,
    inverter_pct: 72, inverter_label: '~72% (est.)',
    non_inverter_pct: 28, non_inverter_label: '~28% (est.)',
    confidence: 'Medium', is_estimate: true,
    scope_notes: '[EST] Source states ">70%"; estimate 72% used as conservative lower bound. Split-type RAC only. S. Africa outlier in Africa driven by high Eskom tariffs making inverter running-cost savings critical. Split ACs ~90% of S. Africa market.',
    source_name: 'iClimaAir – World AC Market Africa (2022 JARN data)',
    source_url: 'https://www.iclimaair.com/nd.jsp?id=84',
  },
  {
    region: 'Africa', country_code: 'NGA', country_name: 'Nigeria',
    year_label: '~2023', year_start: 2023, year_end: 2023,
    inverter_pct: 25, inverter_label: '~25% (est.)',
    non_inverter_pct: 75, non_inverter_label: '~75% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Source states "<30%"; estimate 25% used. Split AC dominant (~90% of mkt). Non-inverter dominant: avg Lagos income ~USD 280/mo makes 20–25% inverter price premium prohibitive. AC imports +17% p.a. since 2020 (NBS). ~840K units.',
    source_name: 'MarkntelAdvisors / Nigeria AC Market',
    source_url: 'https://www.marknteladvisors.com/research-library/nigeria-air-conditioner-market.html',
  },
  {
    region: 'Africa', country_code: 'EGY', country_name: 'Egypt',
    year_label: '2022', year_start: 2022, year_end: 2022,
    inverter_pct: 15, inverter_label: '~15% (est.)',
    non_inverter_pct: 85, non_inverter_label: '~85% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: '[EST] LBNL "Cooling Egypt" report (2022): "Egypt\'s market is still dominated by inefficient fixed-speed drive (FSD) RACs due to a price-sensitive market." LBNL recommends Egypt adopt CSPF/SEER (currently no SEER MEPS). ~960K units (largest African market). Estimate: 10–25% inverter; midpoint 15% used.',
    source_name: 'LBNL – Cooling Egypt (Technical Report, Oct 2022)',
    source_url: 'https://www.osti.gov/biblio/1895348',
  },
  {
    region: 'Africa', country_code: 'TUN', country_name: 'Tunisia',
    year_label: '2022–23', year_start: 2022, year_end: 2023,
    inverter_pct: 34, inverter_label: '34%',
    non_inverter_pct: 66, non_inverter_label: '66%',
    confidence: 'High', is_estimate: false,
    scope_notes: 'DIRECT SOURCED DATA (LBNL). "Variable-speed technology (inverters) has a limited market presence in Tunisia at 34%" based on assessment of 128 models on the Tunisian market. Peak electricity demand Aug 2021 = 4,472 MW; 44% due to AC.',
    source_name: 'LBNL – Tunisia AC Market Assessment (May 2023)',
    source_url: 'https://eta-publications.lbl.gov/sites/default/files/ac_market_assess_tunisia_may_2023.pdf',
  },
  {
    region: 'Africa', country_code: 'MAR', country_name: 'Morocco',
    year_label: '2022–23', year_start: 2022, year_end: 2023,
    inverter_pct: 22, inverter_label: '~22% (est.)',
    non_inverter_pct: 78, non_inverter_label: '~78% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] CLASP: "penetration of inverter technologies is low in most African countries." Morocco MEPS since June 2018 (Thermal Construction Regs) but enforcement limited. Morocco AC Buyers Club pilot (2022) focused on efficient inverter procurement. Midpoint of 15–30% range used.',
    source_name: 'CLASP – Africa AC Market Scoping Study (iClimaAir 2022 JARN data)',
    source_url: 'https://www.clasp.ngo/updates/clasp-africa-air-conditioner-market-scoping-study-sheds-light-on-growing-ac-markets-in-africa/',
  },
  {
    region: 'Africa', country_code: 'DZA', country_name: 'Algeria',
    year_label: '2021–23', year_start: 2021, year_end: 2023,
    inverter_pct: 15, inverter_label: '~15% (est.)',
    non_inverter_pct: 85, non_inverter_label: '~85% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Algeria = 3rd-largest Africa market (600K+ units in 2021). Local brands (Condor, Iris) and Chinese imports dominate. No SEER/inverter-specific MEPS. Very low electricity tariff (heavily subsidised) = minimal consumer incentive for inverter premium. Midpoint of 10–20% range used.',
    source_name: 'iClimaAir – World AC Market Africa (2022 JARN data)',
    source_url: 'https://www.iclimaair.com/nd.jsp?id=84',
  },
  {
    region: 'Africa', country_code: 'LBY', country_name: 'Libya',
    year_label: '2022–24', year_start: 2022, year_end: 2024,
    inverter_pct: 15, inverter_label: '~15% (est.)',
    non_inverter_pct: 85, non_inverter_label: '~85% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Market ~677K units (2024). Import price avg ~$188/unit (very low = non-inverter). Hommer/Gree budget brands dominate. No functional MEPS enforcement due to political instability. Midpoint of 10–20% range used.',
    source_name: 'MarkNtel Advisors – Libya AC Market',
    source_url: 'https://www.marknteladvisors.com/research-library/libya-air-conditioner-market.html',
  },

  // ── MIDDLE EAST ────────────────────────────────────────────────────────────
  {
    region: 'Middle East', country_code: null, country_name: 'Middle East (overall)',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 59.4, inverter_label: '59.4%',
    non_inverter_pct: 40.6, non_inverter_label: '40.6%',
    confidence: 'Medium', is_estimate: false,
    scope_notes: 'SOURCED: Grand View Research "Middle East Air Conditioning Systems Market Report 2033": "inverter-based AC segment held the largest share at 59.4% in 2024." Covers all AC types (split + VRF + cassette + window). Split-only inverter share is likely higher (~65–70%). Market: USD 4,021.7M in 2024.',
    source_name: 'Grand View Research – Middle East Air Conditioning Systems Market Report 2033',
    source_url: 'https://www.grandviewresearch.com/industry-analysis/middle-east-air-conditioning-systems-market-report',
  },
  {
    region: 'Middle East', country_code: 'SAU', country_name: 'Saudi Arabia',
    year_label: 'pre-2022', year_start: null, year_end: 2022,
    inverter_pct: 28, inverter_label: '~28% (est.)',
    non_inverter_pct: 72, non_inverter_label: '~72% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Academic study (PMC): "fixed-speed dominated prior to SEER-MEPS adoption." SASO 2663:2021 SEER labelling mandatory from April–July 2022. Pre-SEER market was heavily non-inverter. Range 20–35%; midpoint 28% used.',
    source_name: 'PMC – Transitioning to High Efficiency AC in Saudi Arabia',
    source_url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7185004/',
  },
  {
    region: 'Middle East', country_code: 'SAU', country_name: 'Saudi Arabia',
    year_label: '2022', year_start: 2022, year_end: 2022,
    inverter_pct: 55, inverter_label: '~55% (est.)',
    non_inverter_pct: 45, non_inverter_label: '~45% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: '[EST] Transition year: SASO 2663:2021 SEER energy labelling mandatory April–July 2022. SEER inherently favours inverter (seasonal metric). Inverter sales grew +40% YoY per Astute Analytica. Midpoint of 50–60% range used.',
    source_name: 'TÜV Rheinland / Astute Analytica – Saudi Arabia AC Market',
    source_url: 'https://www.tuv.com/regulations-and-standards/en/saudi-arabia-update-of-saso-energy-efficiency-standard-for-air-conditioners.html',
  },
  {
    region: 'Middle East', country_code: 'SAU', country_name: 'Saudi Arabia',
    year_label: '2023', year_start: 2023, year_end: 2023,
    inverter_pct: 62, inverter_label: '~62% (est.)',
    non_inverter_pct: 38, non_inverter_label: '~38% (est.)',
    confidence: 'Medium', is_estimate: true,
    scope_notes: '[EST] Inverter technology leads Saudi AC segment per multiple commercial reports. SEER mandatory since 2022; "inverter leads the technology segment." High income levels absorb 20–35% inverter price premium. Split AC = ~60% of total Saudi AC market. Midpoint of 60–65% range used.',
    source_name: 'Astute Analytica / GlobeNewsWire – Saudi Arabia AC Market 2033',
    source_url: 'https://www.globenewswire.com/news-release/2025/02/24/3031287/0/en/Saudi-Arabia-Air-Conditioner-Market-to-Hit-Valuation-of-US-5-969.25-Million-By-2033-Astute-Analytica.html',
  },
  {
    region: 'Middle East', country_code: 'SAU', country_name: 'Saudi Arabia',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 67, inverter_label: '~67% (est.)',
    non_inverter_pct: 33, non_inverter_label: '~33% (est.)',
    confidence: 'Medium', is_estimate: true,
    scope_notes: '[EST] GCC-wide inverter growth + SASO 2663:2021 SEER mandate fully embedded. Market largest in MENA: 21% of MENA inverter market share. Inverter sales grew +40% YoY per Astute Analytica 2024. Midpoint of 65–70% range used.',
    source_name: 'Astute Analytica / GlobeNewsWire – Saudi Arabia AC Market 2033',
    source_url: 'https://www.globenewswire.com/news-release/2025/02/24/3031287/0/en/Saudi-Arabia-Air-Conditioner-Market-to-Hit-Valuation-of-US-5-969.25-Million-By-2033-Astute-Analytica.html',
  },
  {
    region: 'Middle East', country_code: 'ARE', country_name: 'UAE',
    year_label: '2023', year_start: 2023, year_end: 2023,
    inverter_pct: 64, inverter_label: '~64% (est.)',
    non_inverter_pct: 36, non_inverter_label: '~36% (est.)',
    confidence: 'Medium', is_estimate: true,
    scope_notes: '[EST] UAE ESMA energy label programme (UAE.S 5010-1:2019) mandatory from Jan 2021. Smart ACs = 30% of total UAE market. Split systems ~65% of total sales. Inverter technology gains traction due to ESMA compliance. Midpoint of 60–68% used.',
    source_name: 'UL Solutions – UAE Enforcement of Energy Efficiency Standards for ACs',
    source_url: 'https://www.ul.com/news/united-arab-emirates-enforcement-new-energy-efficiency-standards-air-conditioners',
  },
  {
    region: 'Middle East', country_code: 'ARE', country_name: 'UAE',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 68, inverter_label: '~68% (est.)',
    non_inverter_pct: 32, non_inverter_label: '~32% (est.)',
    confidence: 'Medium', is_estimate: true,
    scope_notes: '[EST] Inverter segment within split AC growing strongly. UAE market USD 3,144M by 2033. Daikin, LG, Mitsubishi inverter products dominate premium segment. Midpoint of 65–72% range used.',
    source_name: 'Astute Analytica / GlobeNewsWire – UAE AC Market 2033',
    source_url: 'https://www.globenewswire.com/news-release/2025/02/28/3034664/0/en/UAE-Air-Conditioner-Market-to-Hit-Valuation-of-US-3-144.03-Million-By-2033-Astute-Analytica.html',
  },
  {
    region: 'Middle East', country_code: 'QAT', country_name: 'Qatar',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 60, inverter_label: '60%',
    non_inverter_pct: 40, non_inverter_label: '40%',
    confidence: 'Medium', is_estimate: false,
    scope_notes: 'SOURCED: Astute Analytica: "energy-efficient inverter ACs now make up 60% of sales in Qatar\'s market." Split systems = 65.3% of Qatar AC market. R-32 refrigerant usage +25% since 2023. Market value USD 354.54M (2024).',
    source_name: 'Astute Analytica / GlobeNewsWire – Qatar AC Market 2033',
    source_url: 'https://www.globenewswire.com/news-release/2025/02/26/3033023/0/en/Qatar-Air-Conditioner-Market-Set-to-Reach-US-626.60-Million-By-2033-Astute-Analytica.html',
  },
  {
    region: 'Middle East', country_code: 'KWT', country_name: 'Kuwait',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 60, inverter_label: '~60% (est.)',
    non_inverter_pct: 40, non_inverter_label: '~40% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: '[EST] Market USD 271M (2024). "Consumers willing to pay up to 15% premium for energy-efficient ACs." GCC-wide regulatory push. Conventional ACs consume ~20% more energy than inverter. Midpoint of 55–65% range used. No standalone split-inverter data published.',
    source_name: 'Astute Analytica / GlobeNewsWire – Kuwait AC Market 2033',
    source_url: 'https://www.globenewswire.com/news-release/2025/02/25/3032030/0/en/Kuwait-Air-Conditioner-Market-is-Poised-to-Surpass-Valuation-of-US-415.90-Million-By-2033-Trends-Competition-Forecasts-Opportunities.html',
  },
  {
    region: 'Middle East', country_code: 'BHR', country_name: 'Bahrain',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 60, inverter_label: '~60% (est.)',
    non_inverter_pct: 40, non_inverter_label: '~40% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: '[EST] "Demand for inverter-based ACs has surged." Split systems = 70% of Bahrain AC market. LG inverter ACs = best-selling models. Over 5,000 inverter units installed in affordable housing in 2024. Market USD 90M. Midpoint of 55–65% range used.',
    source_name: 'Astute Analytica / GlobeNewsWire – Bahrain AC Market 2033',
    source_url: 'https://www.globenewswire.com/news-release/2025/02/27/3033647/0/en/Bahrain-Air-Conditioner-Market-is-Poised-to-Reach-Valuation-of-US-127.97-Million-By-2033-Astute-Analytica.html',
  },
  {
    region: 'Middle East', country_code: 'OMN', country_name: 'Oman',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 60, inverter_label: '~60% (est.)',
    non_inverter_pct: 40, non_inverter_label: '~40% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: '[EST] Market ~USD 495M (2024). "Growing popularity of inverter technology" cited as key trend by MarkNtel. Oman = 3rd-largest GCC market by volume (~392K units in 2024). Midpoint of 55–65% range. No published split-inverter standalone figure.',
    source_name: 'MarkNtel Advisors – Oman Air Conditioner Market',
    source_url: 'https://www.marknteladvisors.com/research-library/oman-air-conditioner-market.html',
  },
  {
    region: 'Middle East', country_code: 'JOR', country_name: 'Jordan',
    year_label: '2023–24', year_start: 2023, year_end: 2024,
    inverter_pct: 42, inverter_label: '~42% (est.)',
    non_inverter_pct: 58, non_inverter_label: '~58% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Jordan developing MEPS/labelling regulations in line with EU standards. UNDP Cool Up programme targets efficient AC with natural refrigerants. No ESMA/SASO-equivalent regulation enforced at scale. Income lower than GCC; price sensitivity limits inverter uptake. Midpoint of 35–50% range used.',
    source_name: 'UNDP Cool Up Programme – Jordan',
    source_url: 'https://www.coolupprogramme.org/countries/jordan/',
  },
  {
    region: 'Middle East', country_code: 'IRQ', country_name: 'Iraq',
    year_label: '2022–23', year_start: 2022, year_end: 2023,
    inverter_pct: 37, inverter_label: '~37% (est.)',
    non_inverter_pct: 63, non_inverter_label: '~63% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Iraq AC market was heavily non-inverter prior to recent inverter awareness growth. Subsidised electricity (very low tariff) reduces payback period appeal of inverter premium. Chinese non-inverter imports historically dominant. Midpoint of 30–45% range used.',
    source_name: 'IndexBox – Middle East AC Market Overview 2024',
    source_url: 'https://www.indexbox.io/blog/window-wall-or-split-air-conditioning-system-middle-east-market-overview-2024-10/',
  },
  {
    region: 'Middle East', country_code: 'IRQ', country_name: 'Iraq',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 47, inverter_label: '~47% (est.)',
    non_inverter_pct: 53, non_inverter_label: '~53% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: '[EST] Iraq = largest MENA AC consumer by volume (2.6–2.7M units in 2024, USD 931M). Wall-mounted split = dominant segment. "Higher demand for inverter models" noted, but grid reliability issues reduce consumer willingness to pay inverter premium. No MEPS enforcement. Midpoint of 40–55% range used.',
    source_name: '6Wresearch – Iraq AC Market 2018–2024',
    source_url: 'https://www.6wresearch.com/industry-report/iraq-air-conditioner-market-2018-2024-ac-forecast-by-product-type-window-split-ducted-ductless-centralized-vrf-ahu-fcu-applications-regions-competitive-landscape',
  },
  {
    region: 'Middle East', country_code: 'IRN', country_name: 'Iran',
    year_label: '2022–24', year_start: 2022, year_end: 2024,
    inverter_pct: 32, inverter_label: '~32% (est.)',
    non_inverter_pct: 68, non_inverter_label: '~68% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Domestic manufacturers (Iran Radiator, Emerald Aidin, etc.) produce both inverter and non-inverter splits. Market HHI = 7,676 (highly concentrated). Sanctions limit foreign brand availability, pushing consumers to domestic inverter models. Market surged to USD 68M (2024), +67% YoY. Midpoint of 25–40% range used.',
    source_name: 'Statista – Iran AC Market',
    source_url: 'https://www.statista.com/statistics/910822/iran-ac-demand-volume/',
  },

  // ── EUROPE ─────────────────────────────────────────────────────────────────
  {
    region: 'Europe', country_code: null, country_name: 'Europe (overall)',
    year_label: '2021', year_start: 2021, year_end: 2021,
    inverter_pct: 85, inverter_label: '~85% (est.)',
    non_inverter_pct: 15, non_inverter_label: '~15% (est.)',
    confidence: 'Medium', is_estimate: true,
    scope_notes: '[EST] EU Ecodesign Regulation 206/2012 Tier 2 (Jan 2014) set SEER ≥5.1 for split AC ≤12kW — threshold practically only achievable with inverter compressors. New split AC sales in EU approached 90–95%+ inverter for residential by 2018. 7.45M RAC units, +4.9%. Eastern EU markets drag average down.',
    source_name: 'ZERO US Partners (JARN 2021) + EU Ecodesign context',
    source_url: 'https://zeroac.us/world-air-conditioner-market/',
  },
  {
    region: 'Europe', country_code: null, country_name: 'Europe (overall)',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 87, inverter_label: '~87% (est.)',
    non_inverter_pct: 13, non_inverter_label: '~13% (est.)',
    confidence: 'Medium', is_estimate: true,
    scope_notes: '[EST] EU Ecodesign structural mandate: virtually all new ≤12kW split AC sales in EU must be inverter since ~2016. Lower range applies only to Eastern/lower-income EU markets. EU Ecodesign + REPowerEU heat pump mandate accelerating inverter share further.',
    source_name: 'IIF/JARN – Global AC Market 2024 + EU Ecodesign (Regulation 206/2012)',
    source_url: 'https://iifiir.org/en/news/global-air-conditioner-market-2024-performance',
  },
  {
    region: 'Europe', country_code: 'ITA', country_name: 'Italy',
    year_label: '2018', year_start: 2018, year_end: 2018,
    inverter_pct: 80, inverter_label: '~80%',
    non_inverter_pct: 20, non_inverter_label: '~20%',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'Italy is the largest single-split AC market in Europe. eJARN/CoAer/ANIMA trade data. EU Ecodesign Tier 2 (2014) = structural driver. Inverter penetration already very high by 2018.',
    source_name: 'eJARN – Italy AC Market Special 2018',
    source_url: 'https://www.ejarn.com/article/detail/59490',
  },
  {
    region: 'Europe', country_code: 'ITA', country_name: 'Italy',
    year_label: '2022', year_start: 2022, year_end: 2022,
    inverter_pct: 87, inverter_label: '~87% (est.)',
    non_inverter_pct: 13, non_inverter_label: '~13% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Record year: 1.92M split units sold (driven by Italian Superbonus 110% renovation subsidy). Assoclima/ANIMA confirmed monosplit/multisplit dominance. Inverter technology de facto standard in Italian monosplit market.',
    source_name: 'Assoclima/ANIMA – Italy HVAC Market Survey 2022',
    source_url: 'https://www.anima.it/media/comunicati-stampa/mercato-climatizzazione-presentati-risultati-indagine-assoclima-2024.kl',
  },
  {
    region: 'Europe', country_code: 'ITA', country_name: 'Italy',
    year_label: '2023', year_start: 2023, year_end: 2023,
    inverter_pct: 91, inverter_label: '~91% (est.)',
    non_inverter_pct: 9, non_inverter_label: '~9% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Post-Superbonus correction year; volumes declined but inverter share continued rising. Monosplit/multisplit remained dominant product. Midpoint of 89–93% range used.',
    source_name: 'Assoclima 2023 data (via infobuild.it)',
    source_url: 'https://www.infobuild.it/climatizzazione-italia-opportunita-e-nuove-sfide/',
  },
  {
    region: 'Europe', country_code: 'ITA', country_name: 'Italy',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 92, inverter_label: '~92% (est.)',
    non_inverter_pct: 8, non_inverter_label: '~8% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Monosplit +10% volume, multisplit +13% volume in 2024. Direct expansion = >60% of Italian AC turnover. Italian market has been inverter-dominated since ~2012–2015. Midpoint of 90–95% range used.',
    source_name: 'Assoclima 2024 Survey / ANIMA (industriaeformazione.it)',
    source_url: 'https://industriaeformazione.it/2025/04/07/mercato-climatizzazione-presentati-i-risultati-dellindagine-assoclima-2024/',
  },
  {
    region: 'Europe', country_code: 'ESP', country_name: 'Spain',
    year_label: '2022', year_start: 2022, year_end: 2022,
    inverter_pct: 85, inverter_label: '~85% (est.)',
    non_inverter_pct: 15, non_inverter_label: '~15% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] AFEC Annual Market Report 2022: Spanish HVAC market +21.4%; residential sector 978,958 units at €739M. Spain fastest-growing AC market in Europe (Eurovent 2023). EU Ecodesign mandates inverter for virtually all new ≤12kW split AC. Midpoint of 80–90% range used.',
    source_name: 'AFEC – Spain HVAC Annual Market Report 2022',
    source_url: 'https://www.afec.es/es/mercado-2022',
  },
  {
    region: 'Europe', country_code: 'ESP', country_name: 'Spain',
    year_label: '2023', year_start: 2023, year_end: 2023,
    inverter_pct: 87, inverter_label: '~87% (est.)',
    non_inverter_pct: 13, non_inverter_label: '~13% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] AFEC 2023: Residential 1,275,428 units at €921M; market +18.1%. Fastest-growing AC market in Europe per Eurovent. Midpoint of 83–92% range used.',
    source_name: 'AFEC – Spain HVAC Annual Market Report 2023',
    source_url: 'https://www.afec.es/es/mercado-2023',
  },
  {
    region: 'Europe', country_code: 'ESP', country_name: 'Spain',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 89, inverter_label: '~89% (est.)',
    non_inverter_pct: 11, non_inverter_label: '~11% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] AFEC 2024: Market stagnated; aerothermy and heat pump split systems remain dominant driver. Midpoint of 85–93% range used.',
    source_name: 'AFEC – Spain HVAC Annual Market Report 2024',
    source_url: 'https://www.afec.es/en/mercado-2024',
  },
  {
    region: 'Europe', country_code: 'FRA', country_name: 'France',
    year_label: '2022–24', year_start: 2022, year_end: 2024,
    inverter_pct: 84, inverter_label: '~84% (est.)',
    non_inverter_pct: 16, non_inverter_label: '~16% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] UNICLIMA: >850,000 external split/monosplit units installed in 2023. ~500,000 reversible AC units sold annually. French market is "air-to-air heat pump" dominated — ALL modern reversible splits sold in France are inverter by EU regulatory necessity (EU Ecodesign SEER ≥5.1 since 2014). Midpoint of 78–90% range used.',
    source_name: 'UNICLIMA France – Key Figures',
    source_url: 'https://www.uniclima.fr/chiffres-cles.html',
  },
  {
    region: 'Europe', country_code: 'GRC', country_name: 'Greece',
    year_label: '2022–24', year_start: 2022, year_end: 2024,
    inverter_pct: 86, inverter_label: '~86% (est.)',
    non_inverter_pct: 14, non_inverter_label: '~14% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Greece AC market revenue USD 217.5M in 2024. Greece imports ~981K units/year. Split type dominates. Follows EU Ecodesign rules; inverter penetration high. Lower-income segments retain some fixed-speed residual vs. Germany/France. Midpoint of 80–92% range used.',
    source_name: 'Statista – Greece AC Market',
    source_url: 'https://www.statista.com/outlook/cmo/household-appliances/major-appliances/air-conditioners/greece',
  },
  {
    region: 'Europe', country_code: 'TUR', country_name: 'Turkey',
    year_label: '2022', year_start: 2022, year_end: 2022,
    inverter_pct: 76, inverter_label: '~76% (est.)',
    non_inverter_pct: 24, non_inverter_label: '~24% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: '[EST] ISKID 2022 HVAC\'R Industry Report: "significant demand increase for A++ inverter split units"; 130% production increase over 5 years. Turkey is major producer: ~2M units/year split production. Not EU member — EU Ecodesign does not apply, but Turkey adopted own A++ standard. Midpoint of 70–82% used.',
    source_name: 'ISKID – Turkey 2022 HVAC\'R Industry Report',
    source_url: 'https://iskid.org.tr/en/2022-turkey-hvacr-industry-report/',
  },
  {
    region: 'Europe', country_code: 'TUR', country_name: 'Turkey',
    year_label: '2023', year_start: 2023, year_end: 2023,
    inverter_pct: 78, inverter_label: '~78% (est.)',
    non_inverter_pct: 22, non_inverter_label: '~22% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: '[EST] ISKID 2023: Split AC domestic market ~1.9M units (+5%). Production 2M units. Inverter share growing rapidly. Midpoint of 72–85% range used.',
    source_name: 'ISKID – Turkey 2023 Statistics',
    source_url: 'https://iskid.org.tr/iskid-2023-iklimlendirme-istatistik-sonuclari/',
  },
  {
    region: 'Europe', country_code: 'DEU', country_name: 'Germany',
    year_label: '2022–23', year_start: 2022, year_end: 2023,
    inverter_pct: 71, inverter_label: '~71% (est.)',
    non_inverter_pct: 29, non_inverter_label: '~29% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Germany historically a small residential split AC market (dominated by VRF and commercial HVAC). Residential split AC market was nascent but growing. Germany commands 17.12% of Europe\'s total AC equipment market. EU Ecodesign compliance mandatory. Midpoint of 65–78% range used.',
    source_name: 'Eurovent Market Intelligence / Expert Market Research – Germany AC Market',
    source_url: 'https://www.expertmarketresearch.com/reports/germany-air-conditioner-market',
  },
  {
    region: 'Europe', country_code: 'DEU', country_name: 'Germany',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 78, inverter_label: '~78% (est.)',
    non_inverter_pct: 22, non_inverter_label: '~22% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Residential AC penetration jumped ~45% in 2024 after extreme summer heat. Consumers choosing inverter for energy cost control. Midpoint of 72–85% range used.',
    source_name: 'Expert Market Research – Germany Air Conditioner Market',
    source_url: 'https://www.expertmarketresearch.com/reports/germany-air-conditioner-market',
  },
  {
    region: 'Europe', country_code: 'GBR', country_name: 'United Kingdom',
    year_label: '2022–23', year_start: 2022, year_end: 2023,
    inverter_pct: 84, inverter_label: '~84% (est.)',
    non_inverter_pct: 16, non_inverter_label: '~16% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] UK domestic AC market: 765K units at USD 243M (2023). UK retained EU Ecodesign standards post-Brexit. Modern split AC installs virtually all inverter. Midpoint of 78–90% range used.',
    source_name: 'RAC Plus – UK Domestic AC Market Analysis 2023',
    source_url: 'https://www.racplus.com/news/uk-domestic-ac-market-ripe-for-growth-analysis-finds-26-01-2023/',
  },
  {
    region: 'Europe', country_code: 'GBR', country_name: 'United Kingdom',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 86, inverter_label: '~86% (est.)',
    non_inverter_pct: 14, non_inverter_label: '~14% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] EHPA 2024: UK heat pump sales grew +63%. Split AC market forecast 1.1% CAGR. Inverter dominant for all new split installs. Midpoint of 80–92% used.',
    source_name: 'IndexBox / EHPA – UK AC Market 2024',
    source_url: 'https://www.indexbox.io/blog/window-wall-or-split-air-conditioning-system-united-kingdom-market-overview-2024-9/',
  },
  {
    region: 'Europe', country_code: 'POL', country_name: 'Poland',
    year_label: '2022–24', year_start: 2022, year_end: 2024,
    inverter_pct: 72, inverter_label: '~72% (est.)',
    non_inverter_pct: 28, non_inverter_label: '~28% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Poland: 2nd largest AC producer in Europe (427K units produced, 458K imported in 2024). EU Ecodesign compliance mandatory. Cost sensitivity means non-inverter still has larger residual share vs. Western Europe. Midpoint of 65–80% range used.',
    source_name: 'Mordor Intelligence / EU mandate – Poland HVAC Market',
    source_url: 'https://www.mordorintelligence.com/industry-reports/poland-hvac-market',
  },
  {
    region: 'Europe', country_code: 'ROU', country_name: 'Romania',
    year_label: '2022–24', year_start: 2022, year_end: 2024,
    inverter_pct: 69, inverter_label: '~69% (est.)',
    non_inverter_pct: 31, non_inverter_label: '~31% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Romania: 657K units imported (14% of EU total with Poland combined). Emerging market; fastest-growing penetration. Higher share of budget-grade fixed-speed units vs. Western EU. EU Ecodesign applies but enforcement and market maturity lag. Midpoint of 60–78% range used.',
    source_name: 'IndexBox – Europe AC Market Overview 2024',
    source_url: 'https://www.indexbox.io/blog/window-wall-or-split-air-conditioning-system-europe-market-overview-2024-3/',
  },
  {
    region: 'Europe', country_code: 'PRT', country_name: 'Portugal',
    year_label: '2022–24', year_start: 2022, year_end: 2024,
    inverter_pct: 86, inverter_label: '~86% (est.)',
    non_inverter_pct: 14, non_inverter_label: '~14% (est.)',
    confidence: 'Low', is_estimate: true,
    scope_notes: '[EST] Portugal AC market USD 241M in 2024; 6.58% CAGR. One of only 3 European markets with heat pump/AC growth in 2024. Tourism and residential sector driving demand. Modern split installs virtually all inverter. Midpoint of 80–92% range used.',
    source_name: 'Statista / EHPA – Portugal AC Market',
    source_url: 'https://www.statista.com/statistics/721687/ac-demand-units-portugal/',
  },

  // ── NORTH AMERICA ──────────────────────────────────────────────────────────
  {
    region: 'North America', country_code: 'USA', country_name: 'USA (mini-split)',
    year_label: '2021', year_start: 2021, year_end: 2021,
    inverter_pct: 90, inverter_label: '~90% (est.)',
    non_inverter_pct: 10, non_inverter_label: '~10% (est.)',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'Mini-split segment only (the split AC equivalent in the USA; ducted central AC excluded). Mini-splits sold in USA are predominantly inverter by design. DOE SEER2 standards (effective Jan 2023) strongly favour inverter. Traditional unitary: ~4% inverter (separate segment).',
    source_name: 'ZERO US Partners (JARN 2021) + product architecture context',
    source_url: 'https://zeroac.us/world-air-conditioner-market/',
  },
  {
    region: 'North America', country_code: 'USA', country_name: 'USA (mini-split)',
    year_label: '2023–24', year_start: 2023, year_end: 2024,
    inverter_pct: 92, inverter_label: '~92% (est.)',
    non_inverter_pct: 8, non_inverter_label: '~8% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: '[EST] GMI Insights: "Inverter mini-splits held largest revenue share in 2024." Market size USD 1.4B (2024). NOTE: virtually ALL mini-splits sold by major brands (Daikin, Mitsubishi, LG) are variable-speed by design. US mini-split market declined 3.7% in 2024 (IIF). DOE SEER2 from Jan 2023.',
    source_name: 'GMI Insights – U.S. Mini Split AC Market / IIF 2024',
    source_url: 'https://www.gminsights.com/industry-analysis/us-mini-split-air-conditioning-system-market',
  },

  // ── GLOBAL ─────────────────────────────────────────────────────────────────
  {
    region: 'Global', country_code: null, country_name: 'Global',
    year_label: '2018', year_start: 2018, year_end: 2018,
    inverter_pct: 42.5, inverter_label: '~40–45%',
    non_inverter_pct: 57.5, non_inverter_label: '~55–60%',
    confidence: 'Estimate', is_estimate: true,
    scope_notes: 'All RAC (split dominant globally). Total 130.1M units (+0.6% YoY). Global figure estimated; not stated explicitly in source.',
    source_name: 'IIF/JARN – World AC Market Trends (Jan 2019)',
    source_url: 'https://iifiir.org/en/news/world-air-conditioning-market-figures-and-technical-trends',
  },
  {
    region: 'Global', country_code: null, country_name: 'Global',
    year_label: '2021', year_start: 2021, year_end: 2021,
    inverter_pct: 62, inverter_label: '~62% (est.)',
    non_inverter_pct: 38, non_inverter_label: '~38% (est.)',
    confidence: 'Low-Medium', is_estimate: true,
    scope_notes: '[EST] Weighted estimate from known country shares: China 73.5% (50.3M), USA mini-split ~90% overall very low (24.3M mostly ducted), SE Asia ~55% (11.2M), Japan ~100% (9.9M), LatAm ~40% (9.4M), Europe ~85% (8M), Africa ~18% (3.4M). Total 126.1M units (+3.0%). R32 penetration >70%.',
    source_name: 'IIF/JARN – Global AC Market (2021)',
    source_url: 'https://iifiir.org/en/news/the-global-air-conditioning-market-in-2021-focus-on-africa',
  },
  {
    region: 'Global', country_code: null, country_name: 'Global (split AC)',
    year_label: '2023', year_start: 2023, year_end: 2023,
    inverter_pct: 65, inverter_label: '~65%',
    non_inverter_pct: 35, non_inverter_label: '~35%',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'Split Air Conditioning System Market specifically (not all AC types). "In 2023, the inverter technology segment accounted for approximately 65% of the Split Air Conditioning System Market revenue." Total global split AC market revenue: USD 73B+ in 2023.',
    source_name: 'Market Research Future / SkyQuest – Split AC Systems Market',
    source_url: 'https://www.skyquestt.com/report/split-air-conditioning-systems-market',
  },
  {
    region: 'Global', country_code: null, country_name: 'Global',
    year_label: '2024', year_start: 2024, year_end: 2024,
    inverter_pct: 70.55, inverter_label: '~70.55%',
    non_inverter_pct: 29.45, non_inverter_label: '~29.45%',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'All RAC. Total 140.58M units (+4% YoY). Grand View Research 68.6% (2024), Mordor Intelligence 70.55% (2024). Asia-Pacific 45.61% of global revenue. Inverter CAGR 9.1% vs non-inverter 3.0% (2025–33).',
    source_name: 'Grand View Research / Mordor Intelligence (Jan 2025)',
    source_url: 'https://www.grandviewresearch.com/industry-analysis/air-conditioning-systems-industry',
  },
  {
    region: 'Global', country_code: null, country_name: 'Global',
    year_label: '2025', year_start: 2025, year_end: 2025,
    inverter_pct: 71.85, inverter_label: '~71.85%',
    non_inverter_pct: 28, non_inverter_label: '~28%',
    confidence: 'Medium', is_estimate: true,
    scope_notes: 'All AC shipments (Mordor Intelligence base-year figure). Inverter CAGR 7.57% vs non-inverter through 2031. Asia-Pacific 47% of global revenue.',
    source_name: 'Mordor Intelligence – AC Market Report',
    source_url: 'https://www.mordorintelligence.com/industry-reports/air-conditioner-market',
  },
];

// ── main ─────────────────────────────────────────────────────────────────────
async function main() {
  console.log(`Inserting ${ROWS.length} rows into ac_inverter_share...`);
  const inserted = await insertBatch('ac_inverter_share', ROWS);
  console.log(`\nDone. Inserted ${inserted} rows.`);
  console.log('\nCountry code coverage:');
  const withCode = ROWS.filter(r => r.country_code).length;
  const noCode   = ROWS.filter(r => !r.country_code).length;
  console.log(`  With ISO Alpha-3 code : ${withCode}`);
  console.log(`  Regional aggregates   : ${noCode}`);
}

main().catch(err => {
  console.error('Error:', err.message);
  process.exit(1);
});
